const Complaint = require("../models/complaint");
const User = require("../models/user");
const Notification = require("../models/notification");
const { analyzeComplaint } = require("../services/aiService");

const respondError = (res, status, message) => res.status(status).json({ success: false, message });
const setStatus = (complaint, status, user, note = "") => {
  if (complaint.status === status) return false;
  complaint.status = status;
  complaint.statusHistory.push({ status, changedBy: user, changedAt: new Date(), note });
  return true;
};
const notify = (c, type, title, message) => Notification.create({ recipient: c.student, complaint: c._id, type, title, message });
const detailed = query => query.populate("student", "name email studentId department year").populate("assignedTo approvedBy rejectedBy", "name email role").populate("comments.author", "name email role");

exports.createComplaint = async (req, res) => {
  try {
    const { title, description, category = "Other", priority = "Medium", department = "Administration" } = req.body;
    if (!title?.trim() || !description?.trim()) return respondError(res, 400, "Title and description are required");
    if (title.trim().length > 160 || description.trim().length > 5000) return respondError(res, 400, "Complaint content is too long");
    let ai = {}; try { ai = await analyzeComplaint(title.trim(), description.trim()); } catch (e) { console.error("AI analysis unavailable:", e.message); }
    const images = (req.files || []).map(file => `/uploads/${file.filename}`);
    const c = new Complaint({ student: req.user._id, title: title.trim(), description: description.trim(), category, priority, department, images, status: "Pending Approval", approvalStatus: "pending", statusHistory: [{ status: "Pending Approval", changedBy: req.user._id, note: "Complaint submitted" }], aiAnalysis: { category: ai.category || category, priority: ai.priority || priority, summary: ai.summary || "AI analysis unavailable.", department: ai.department || department, sentiment: ai.sentiment || "Neutral", keywords: ai.keywords || [], similarComplaint: !!ai.similarComplaint, confidence: ai.confidence || 0 } });
    await c.save(); await notify(c, "submitted", "Complaint submitted", `${c.ticketId} is awaiting approval.`);
    res.status(201).json({ success: true, message: "Complaint submitted and awaiting approval.", data: c, complaint: c });
  } catch (e) { console.error("Create complaint:", e); respondError(res, 500, "Server error while submitting complaint"); }
};
exports.getMyComplaints = async (req, res) => { try { const complaints = await Complaint.find({ student: req.user._id }).populate("assignedTo", "name email").sort({ createdAt: -1 }); res.json({ success: true, count: complaints.length, data: complaints, complaints }); } catch (e) { respondError(res, 500, "Could not fetch complaints"); } };
exports.getComplaintById = async (req, res) => { try { const filter = { _id: req.params.id }; if (req.user.role !== "admin") filter.student = req.user._id; const complaint = await detailed(Complaint.findOne(filter)); if (!complaint) return respondError(res, 404, "Complaint not found"); res.json({ success: true, data: complaint, complaint }); } catch (e) { respondError(res, 400, "Invalid complaint ID"); } };
exports.getAllComplaints = async (req, res) => { try { const { status, priority, category, department, search, sort = "newest", pending } = req.query, filter = {}; if (status) filter.status = status; if (priority) filter.priority = priority; if (category) filter.category = category; if (department) filter.department = department; if (pending === "true") filter.approvalStatus = "pending"; if (search?.trim()) { const rx = new RegExp(search.trim(), "i"), people = await User.find({ $or: [{ name: rx }, { studentId: rx }, { email: rx }] }).select("_id"); filter.$or = [{ ticketId: rx }, { title: rx }, { description: rx }, { student: { $in: people.map(p => p._id) } }]; } const complaints = await detailed(Complaint.find(filter).sort(sort === "priority" ? { priority: -1, createdAt: -1 } : { createdAt: -1 })); res.json({ success: true, count: complaints.length, data: complaints, complaints }); } catch (e) { respondError(res, 500, "Could not fetch complaints"); } };
exports.approveComplaint = async (req, res) => { try { const c = await Complaint.findById(req.params.id); if (!c) return respondError(res, 404, "Complaint not found"); if (c.approvalStatus !== "pending") return respondError(res, 400, "Only pending complaints can be approved"); c.approvalStatus = "approved"; c.approvedBy = req.user._id; c.approvedAt = new Date(); setStatus(c, "Under Review", req.user._id, "Approved by administrator"); await c.save(); await notify(c, "approved", "Complaint approved", `${c.ticketId} is now under review.`); res.json({ success: true, message: "Complaint approved", data: c, complaint: c }); } catch (e) { respondError(res, 500, "Could not approve complaint"); } };
exports.rejectComplaint = async (req, res) => { try { const reason = req.body.rejectionReason?.trim(); if (!reason) return respondError(res, 400, "Rejection reason is required"); const c = await Complaint.findById(req.params.id); if (!c) return respondError(res, 404, "Complaint not found"); if (c.approvalStatus !== "pending") return respondError(res, 400, "Only pending complaints can be rejected"); c.approvalStatus = "rejected"; c.rejectionReason = reason; c.rejectedBy = req.user._id; c.rejectedAt = new Date(); setStatus(c, "Rejected", req.user._id, reason); await c.save(); await notify(c, "rejected", "Complaint rejected", `${c.ticketId} was rejected: ${reason}`); res.json({ success: true, message: "Complaint rejected", data: c, complaint: c }); } catch (e) { respondError(res, 500, "Could not reject complaint"); } };
exports.assignComplaint = async (req, res) => { try { const c = await Complaint.findById(req.params.id); if (!c) return respondError(res, 404, "Complaint not found"); if (c.status !== "Under Review") return respondError(res, 400, "Only complaints under review can be assigned"); const assignee = await User.findOne({ _id: req.body.assignedTo, role: { $in: ["admin", "staff"] } }); if (!assignee) return respondError(res, 400, "Assignee must be an admin or staff member"); c.assignedTo = assignee._id; setStatus(c, "Assigned", req.user._id, `Assigned to ${assignee.name}`); await c.save(); await notify(c, "assigned", "Complaint assigned", `${c.ticketId} was assigned to ${assignee.name}.`); res.json({ success: true, message: "Complaint assigned", data: c, complaint: c }); } catch (e) { respondError(res, 400, "Unable to assign complaint"); } };
exports.updateComplaintStatus = async (req, res) => { try { const c = await Complaint.findById(req.params.id), status = req.body.status, valid = { "Under Review": ["Assigned", "Resolved"], "Assigned": ["In Progress", "Resolved"], "In Progress": ["Resolved"] }; if (!c) return respondError(res, 404, "Complaint not found"); if (!valid[c.status]?.includes(status)) return respondError(res, 400, `Invalid transition from ${c.status} to ${status}`); setStatus(c, status, req.user._id, req.body.note?.trim() || "Status updated by administrator"); if (status === "Resolved") c.resolvedAt = new Date(); await c.save(); await notify(c, status === "Resolved" ? "resolved" : "status_changed", status === "Resolved" ? "Complaint resolved" : "Status updated", `${c.ticketId} is now ${status}.`); res.json({ success: true, message: "Complaint status updated", data: c, complaint: c }); } catch (e) { respondError(res, 500, "Could not update status"); } };
exports.addAdminResponse = async (req, res) => { try { const response = req.body.adminResponse?.trim(); if (!response || response.length > 3000) return respondError(res, 400, "A response of up to 3000 characters is required"); const c = await Complaint.findById(req.params.id); if (!c) return respondError(res, 404, "Complaint not found"); c.adminResponse = response; await c.save(); await notify(c, "response", "New admin response", `An administrator replied to ${c.ticketId}.`); res.json({ success: true, message: "Admin response added", data: c, complaint: c }); } catch (e) { respondError(res, 500, "Could not add response"); } };
exports.addComment = async (req, res) => { try { const text = req.body.text?.trim(); if (!text || text.length > 3000) return respondError(res, 400, "A comment of up to 3000 characters is required"); const c = await Complaint.findById(req.params.id); if (!c) return respondError(res, 404, "Complaint not found"); c.comments.push({ author: req.user._id, text }); await c.save(); await notify(c, "comment", "New complaint comment", `An administrator commented on ${c.ticketId}.`); const complaint = await detailed(Complaint.findById(c._id)); res.status(201).json({ success: true, message: "Comment added", data: complaint, complaint }); } catch (e) { console.error("Add complaint comment:", e); respondError(res, 500, "Could not add comment"); } };
exports.getComplaintStats = async (req, res) => { try { const all = await Complaint.find().select("status priority category department"); const n = s => all.filter(c => c.status === s).length, group = key => Object.entries(all.reduce((o, c) => (o[c[key] || "Other"] = (o[c[key] || "Other"] || 0) + 1, o), {})).map(([_id, count]) => ({ _id, count })); const stats = { total: all.length, pendingApproval: n("Pending Approval"), underReview: n("Under Review"), assigned: n("Assigned"), inProgress: n("In Progress"), resolved: n("Resolved"), rejected: n("Rejected"), highPriority: all.filter(c => ["High", "Critical"].includes(c.priority)).length }; res.json({ success: true, data: { stats, categoryStats: group("category"), statusStats: group("status"), departmentStats: group("department"), priorityStats: group("priority") }, stats, categoryStats: group("category") }); } catch (e) { respondError(res, 500, "Could not load statistics"); } };
